
package webcalendar;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebCalendar", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebCalendar {


    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalendar", targetNamespace = "http://service/", className = "webcalendar.GetCalendar")
    @ResponseWrapper(localName = "getCalendarResponse", targetNamespace = "http://service/", className = "webcalendar.GetCalendarResponse")
    @Action(input = "http://service/WebCalendar/getCalendarRequest", output = "http://service/WebCalendar/getCalendarResponse")
    public XMLGregorianCalendar getCalendar();

}
