
package webcalendar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebCalendarService", targetNamespace = "http://service/", wsdlLocation = "http://localhost.localdomain:8080/webCalendar-1.0-SNAPSHOT/WebCalendarService?wsdl")
public class WebCalendarService
    extends Service
{

    private final static URL WEBCALENDARSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBCALENDARSERVICE_EXCEPTION;
    private final static QName WEBCALENDARSERVICE_QNAME = new QName("http://service/", "WebCalendarService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost.localdomain:8080/webCalendar-1.0-SNAPSHOT/WebCalendarService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBCALENDARSERVICE_WSDL_LOCATION = url;
        WEBCALENDARSERVICE_EXCEPTION = e;
    }

    public WebCalendarService() {
        super(__getWsdlLocation(), WEBCALENDARSERVICE_QNAME);
    }

    public WebCalendarService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBCALENDARSERVICE_QNAME, features);
    }

    public WebCalendarService(URL wsdlLocation) {
        super(wsdlLocation, WEBCALENDARSERVICE_QNAME);
    }

    public WebCalendarService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBCALENDARSERVICE_QNAME, features);
    }

    public WebCalendarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebCalendarService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebCalendar
     */
    @WebEndpoint(name = "WebCalendarPort")
    public WebCalendar getWebCalendarPort() {
        return super.getPort(new QName("http://service/", "WebCalendarPort"), WebCalendar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebCalendar
     */
    @WebEndpoint(name = "WebCalendarPort")
    public WebCalendar getWebCalendarPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "WebCalendarPort"), WebCalendar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBCALENDARSERVICE_EXCEPTION!= null) {
            throw WEBCALENDARSERVICE_EXCEPTION;
        }
        return WEBCALENDARSERVICE_WSDL_LOCATION;
    }

}
